"""empty message

Revision ID: bda53d6ff90b
Revises: e22c6acbee3f
Create Date: 2018-03-13 15:23:46.285591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda53d6ff90b'
down_revision = 'e22c6acbee3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RecentActivity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=255), nullable=False),
    sa.Column('spotify_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RecentActivity')
    # ### end Alembic commands ###
