"""empty message

Revision ID: e22c6acbee3f
Revises: ff69a4d37bb7
Create Date: 2018-02-24 21:28:18.120098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e22c6acbee3f'
down_revision = 'ff69a4d37bb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Lyrics', sa.Column('artist', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Lyrics', 'artist')
    # ### end Alembic commands ###
