"""empty message

Revision ID: ede966d6ad29
Revises: 01851511892c
Create Date: 2018-02-18 15:44:31.707343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ede966d6ad29'
down_revision = '01851511892c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LyricRating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('lyrics_id', sa.Integer(), nullable=False),
    sa.Column('rater_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lyrics_id'], ['Lyrics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rater_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LyricRating')
    # ### end Alembic commands ###
