"""empty message

Revision ID: ff69a4d37bb7
Revises: ede966d6ad29
Create Date: 2018-02-23 13:55:49.510255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff69a4d37bb7'
down_revision = 'ede966d6ad29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('num_of_contributions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'num_of_contributions')
    # ### end Alembic commands ###
